src/Entity/Commande.php
<?php

namespace App\Entity;

use App\Repository\CommandeRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CommandeRepository::class)
 */
class Commande
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="date")
     */
    private $creation_date;

    /**
     * @ORM\Column(type="float")
     */
    private $prix_total;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="commandes")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\ManyToMany(targetEntity=Produit::class)
     * @ORM\JoinTable(name="prod_commande",
     *      joinColumns={@ORM\JoinColumn(name="commande_id", referencedColumnName="id")},
     *      inverseJoinColumns={@ORM\JoinColumn(name="prod_id", referencedColumnName="id_produit")}
     * )
     */
    private $listprod;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $state;

    public function __construct()
    {
        $this->listprod = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCreationDate(): ?\DateTimeInterface
    {
        return $this->creation_date;
    }

    public function setCreationDate(\DateTimeInterface $creation_date): self
    {
        $this->creation_date = $creation_date;

        return $this;
    }

    public function getPrixTotal(): ?float
    {
        return $this->prix_total;
    }

    public function setPrixTotal(float $prix_total): self
    {
        $this->prix_total = $prix_total;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection<int, Produit>
     */
    public function getListprod(): Collection
    {
        return $this->listprod;
    }

    public function addListprod(Produit $listprod): self
    {
        if (!$this->listprod->contains($listprod)) {
            $this->listprod[] = $listprod;
        }

        return $this;
    }

    public function removeListprod(Produit $listprod): self
    {
        $this->listprod->removeElement($listprod);

        return $this;
    }

    public function getState(): ?string
    {
        return $this->state;
    }

    public function setState(string $state): self
    {
        $this->state = $state;

        return $this;
    }
}

src/Entity/Produit.php
<?php

namespace App\Entity;

use App\Repository\ProduitRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=ProduitRepository::class)
 */
class Produit
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id_produit;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Get creative and think of a title!")
     */
    private $nom_produit;

    /**
     * @ORM\Column(type="integer")
     * @Assert\NotBlank(message="Get creative and think of a title!")
     */
    private $quantite;

    /**
     * @ORM\Column(type="float")
     * @Assert\NotBlank(message="Get creative and think of a title!")
     */
    private $prix;

    /**
     * @ORM\ManyToOne(targetEntity=Categorie::class, inversedBy="produits")
     */
    private $categorie;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $image;
    private $file;

    public function getId(): ?int
    {
        return $this->id_produit;
    }
    public function getFile(): ?string
    {
        return $this->id;
    }
    public function setFile(string $file): self
    {
        $this->file = $file;

        return $this;
    }

    public function getNomProduit(): ?string
    {
        return $this->nom_produit;
    }

    public function setNomProduit(string $nom_produit): self
    {
        $this->nom_produit = $nom_produit;

        return $this;
    }

    public function getQuantite(): ?int
    {
        return $this->quantite;
    }

    public function setQuantite(int $quantite): self
    {
        $this->quantite = $quantite;

        return $this;
    }

    public function getPrix(): ?float
    {
        return $this->prix;
    }

    public function setPrix(float $prix): self
    {
        $this->prix = $prix;

        return $this;
    }

    public function getCategorie(): ?Categorie
    {
        return $this->categorie;
    }

    public function setCategorie(?Categorie $categorie): self
    {
        $this->categorie = $categorie;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): self
    {
        $this->image = $image;

        return $this;
    }
}

src/Form/CommandeType.php
<?php

namespace App\Form;

use App\Entity\Commande;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CommandeType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder->add('state', ChoiceType::class, [
        'choices' => [
           'waiting'=>'waiting',
           'ongoing'=>'ongoing',
        ]])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Commande::class,
        ]);
    }
}

src/Controller/CommandeController.php
<?php

namespace App\Controller;

use App\Entity\Commande;
use App\Form\CommandeType;
use App\Repository\CommandeRepository;
use phpDocumentor\Reflection\Types\This;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class CommandeController extends AbstractController
{
    /**
     * @Route("/admin/commande/affiche", name="affichecommande")
     */
    public function afficher(CommandeRepository $repository): Response
    {
        return $this->render('commande/index.html.twig', [
            'commandes' => $repository->findAll(),'element'=>'affichercom',
        ]);
    }
    /**
     * @Route("/admin/commande/update/{id}", name="updatecommande")
     */
    public function modifierCommande(Commande $commande,Request $request): Response
    {
       $form=$this->createForm(CommandeType::class,$commande);
       $form->handleRequest($request);
       if($form->isSubmitted() && $form->isValid()){
           $em = $this->getDoctrine()->getManager();
           $em->flush();
           return $this->redirectToRoute('affichecommande');


       }
       return $this->render('commande/update.html.twig',['element'=>'modifCommande','form'=>$form->createView()]);

    }
    /**
     * @Route("/admin/commande/remove/{id}", name="deletecommande")
     */
    public function deleteCommande(Commande $commande): Response
    {
        $em= $this->getDoctrine()->getManager();
        $em->remove($commande);
        $em->flush();
        return $this->redirectToRoute('affichecommande');
    }
    /**
     * @Route("/admin/commande/details/{id}", name="detailscommande")
     */
    public function detailsCommande(Commande $commande): Response
    {
      return $this->render('commande/details.html.twig',['c'=>$commande,'element'=>'details']);
    }
}

templates/commande/details.html.twig
{% extends 'baseAdmin.html.twig' %}

{% block title %}affiche categorie{% endblock %}

{% block body %}



    <div class="container-fluid pt-4 px-4">
        <div class="row ">
            <div class="col">
                <div class="bg-light rounded h-100 p-4">
                    <h6 class="mb-4">total price: {{ c.prixTotal }}</h6>
                    <h6 class="mb-4">state : {{ c.state }}</h6>
                    <h6 class="mb-4">client : {{ c.user.username }}</h6>
                    <table class="table">
                        <thead>
                        <tr>

                            <th scope="col">name</th>
                            <th scope="col">quantity</th>
                            <th scope="col">price</th>
                            <th scope="col">image</th>
                            <th scope="col">categorie</th>

                        </tr>
                        </thead>
                        <tbody>
                        {% for produit in c.listProd %}
                            <tr>

                                <td>{{ produit.nomProduit }}</td>
                                <td>{{ produit.quantite }}</td>
                                <td>{{ produit.prix }}</td>
                                <td><img src="{{ asset(produit.image) }}" width="50" height="50"></td>
                                <td>{{ produit.categorie.name }}</td>


                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>

        </div>
    </div>
{% endblock %}

templates/commande/index.html.twig
{% extends 'baseAdmin.html.twig' %}

{% block title %}affiche categorie{% endblock %}

{% block body %}



    <div class="container-fluid pt-4 px-4">
        <div class="row ">
            <div class="col">
                <div class="bg-light rounded h-100 p-4">
                    <h6 class="mb-4">commandes</h6>
                    <table class="table">
                        <thead>
                        <tr>

                            <th scope="col">total</th>
                            <th scope="col">state</th>
                            <th scope="col">creationDate</th>
                            <th scope="col">username</th>

                            <th scope="col">supprimer</th>
                            <th scope="col">modifier</th>
                            <th scope="col">details</th>

                        </tr>
                        </thead>
                        <tbody>
                        {% for c in commandes %}
                            <tr>

                                <td>{{ c.prixTotal }}</td>
                                <td>{{ c.state }}</td>

                                <td>{{ c.creationDate | date }}</td>
                                <td>{{ c.user.username }}</td>


                                <td><a href="{{ path('deletecommande',{id:c.id}) }}"><button type="button" class="btn btn-danger">delete</button></a></td>
                                <td><a href="{{ path('updatecommande',{id:c.id}) }}"><button type="button" class="btn btn-success">update</button></a></td>
                                <td><a href="{{ path('detailscommande',{id:c.id}) }}">voir details</a></td>

                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>

        </div>
    </div>
{% endblock %}

templates/commande/update.html.twig
{% extends 'baseAdmin.html.twig' %}
{% block body %}

    <div class="container-fluid pt-4 px-4">
        <div class="row">
            <div class="col">
                <div class="bg-light rounded h-100 p-4">
                    <h6 class="mb-4">update commande</h6>
                    {{ form_start(form) }}
                    <div class="mb-3">
                        <label for="exampleInputEmail1" class="form-label">state</label>
                        {{ form_widget(form.state, {'attr': {'class': 'form-control'}}) }}


                    </div>


                    <button type="submit" class="btn btn-primary" style="width: 100%">{% if element == 'ajouter' %}ajouter{% else %}modifier{% endif %}</button>
                    {{ form_end(form) }}
                </div>
            </div>

        </div>
    </div>

    <!-- Form End -->

{% endblock %}