src/Entity/Commande.php
<?php

namespace App\Entity;

use App\Repository\CommandeRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CommandeRepository::class)
 */
class Commande
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="date")
     */
    private $creation_date;

    /**
     * @ORM\Column(type="float")
     */
    private $prix_total;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="commandes")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\ManyToMany(targetEntity=Produit::class)
     * @ORM\JoinTable(name="prod_commande",
     *      joinColumns={@ORM\JoinColumn(name="commande_id", referencedColumnName="id")},
     *      inverseJoinColumns={@ORM\JoinColumn(name="prod_id", referencedColumnName="id_produit")}
     * )
     */
    private $listprod;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $state;

    public function __construct()
    {
        $this->listprod = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCreationDate(): ?\DateTimeInterface
    {
        return $this->creation_date;
    }

    public function setCreationDate(\DateTimeInterface $creation_date): self
    {
        $this->creation_date = $creation_date;

        return $this;
    }

    public function getPrixTotal(): ?float
    {
        return $this->prix_total;
    }

    public function setPrixTotal(float $prix_total): self
    {
        $this->prix_total = $prix_total;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection<int, Produit>
     */
    public function getListprod(): Collection
    {
        return $this->listprod;
    }

    public function addListprod(Produit $listprod): self
    {
        if (!$this->listprod->contains($listprod)) {
            $this->listprod[] = $listprod;
        }

        return $this;
    }

    public function removeListprod(Produit $listprod): self
    {
        $this->listprod->removeElement($listprod);

        return $this;
    }

    public function getState(): ?string
    {
        return $this->state;
    }

    public function setState(string $state): self
    {
        $this->state = $state;

        return $this;
    }
}

src/Entity/Livraison.php
<?php

namespace App\Entity;

use App\Repository\LivraisonRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=LivraisonRepository::class)
 */
class Livraison
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="date")
     */
    private $date_creation;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $state;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="livraisons")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $prixTotal;

    /**
     * @Assert\NotBlank(message="Get creative and think of a title!")
     * @ORM\Column(type="string", length=255)
     */
    private $destination;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateCreation(): ?\DateTimeInterface
    {
        return $this->date_creation;
    }

    public function setDateCreation(\DateTimeInterface $date_creation): self
    {
        $this->date_creation = $date_creation;

        return $this;
    }

    public function getState(): ?string
    {
        return $this->state;
    }

    public function setState(string $state): self
    {
        $this->state = $state;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getPrixTotal(): ?string
    {
        return $this->prixTotal;
    }

    public function setPrixTotal(string $prixTotal): self
    {
        $this->prixTotal = $prixTotal;

        return $this;
    }

    public function getDestination(): ?string
    {
        return $this->destination;
    }

    public function setDestination(string $destination): self
    {
        $this->destination = $destination;

        return $this;
    }
}

src/Controller/LivController.php
<?php

namespace App\Controller;

use App\Entity\Livraison;
use App\Form\LivraisonType;
use App\Repository\LivraisonRepository;
use App\Repository\ProduitRepository;
use App\Repository\UserRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class LivController extends AbstractController
{
    /**
     * @Route("/admin/livraison/affiche", name="affichelivraison")
     */
    public function afficher(LivraisonRepository $repository): Response
    {
        return $this->render('liv/index.html.twig', [
            'livraisons' => $repository->findAll(),'element'=>'afficherliv',
        ]);
    }
    /**
     * @Route("/admin/livraison/update/{id}", name="updatelivraison")
     */
    public function modifierCommande(Livraison $livraison,Request $request): Response
    {
        $form=$this->createForm(LivraisonType::class,$livraison);
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid()){
            $em = $this->getDoctrine()->getManager();
            $em->flush();
            return $this->redirectToRoute('affichelivraison');


        }
        return $this->render('liv/update.html.twig',['element'=>'modifliv','form'=>$form->createView()]);

    }
    /**
     * @Route("/admin/livraison/remove/{id}", name="deletelivraison")
     */
    public function deleteCommande(Livraison $livraison): Response
    {
        $em= $this->getDoctrine()->getManager();
        $em->remove($livraison);
        $em->flush();
        return $this->redirectToRoute('affichelivraison');
    }
    /**
     * @Route("/livraison/new", name="new_livraison")
     */
    public function newLivraison(Request $request,ProduitRepository $repository,UserRepository $userRepository): Response
    {
        $panier = $request->getSession()->get('panier', []);
        $tot = 0;

        $livraison = new Livraison();


        $livraison->setDateCreation(new \DateTime());
        $livraison->setState('waiting');

        $user = $userRepository->find(1);

        foreach ($panier as $item => $quantity) {

            $prod = $repository->find($item);
            $tot = $tot + ($quantity*$prod->getPrix());






        }

        $livraison->setDestination($_POST['dest']);
        $livraison->setPrixTotal($tot);
        $livraison->setUser($user);
        $em=$this->getDoctrine()->getManager();
        $em->persist($livraison);
        $em->flush();

        $request->getSession()->set('panier',[]);
        return $this->redirectToRoute('app_produit');
    }
}

templates/liv/index.html.twig
{% extends 'baseAdmin.html.twig' %}

{% block title %}affiche categorie{% endblock %}

{% block body %}



    <div class="container-fluid pt-4 px-4">
        <div class="row ">
            <div class="col">
                <div class="bg-light rounded h-100 p-4">
                    <h6 class="mb-4">commandes</h6>
                    <table class="table">
                        <thead>
                        <tr>

                            <th scope="col">total</th>
                            <th scope="col">state</th>
                            <th scope="col">creationDate</th>
                            <th scope="col">destination</th>
                            <th scope="col">username</th>

                            <th scope="col">supprimer</th>
                            <th scope="col">modifier</th>


                        </tr>
                        </thead>
                        <tbody>
                        {% for c in livraisons %}
                            <tr>

                                <td>{{ c.prixTotal }}</td>
                                <td>{{ c.state }}</td>

                                <td>{{ c.dateCreation | date }}</td>
                                <td>{{ c.destination }}</td>
                                <td>{{ c.user.username }}</td>


                                <td><a href="{{ path('deletelivraison',{id:c.id}) }}"><button type="button" class="btn btn-danger">supprimer</button></a></td>
                                <td><a href="{{ path('updatelivraison',{id:c.id}) }}"><button type="button" class="btn btn-success">modifier</button></a></td>

                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>

        </div>
    </div>
{% endblock %}

templates/liv/update.html.twig
{% extends 'baseAdmin.html.twig' %}
{% block body %}

    <div class="container-fluid pt-4 px-4">
        <div class="row">
            <div class="col">
                <div class="bg-light rounded h-100 p-4">
                    <h6 class="mb-4">update livraison</h6>
                    {{ form_start(form,{'attr': {'class':'modLiv'}}) }}
                    <div class="mb-3">
                        <label for="exampleInputEmail1" class="form-label">state</label>
                        {{ form_widget(form.state, {'attr': {'class': 'form-control'}}) }}


                    </div>
                    <div class="mb-3">
                        <label for="exampleInputEmail1" class="form-label">destination</label>
                        {{ form_widget(form.destination, {'attr': {'class': 'form-control dest'}}) }}
                        <p style="color: red;display: none;" class="error" > this field cannot be null </p>


                    </div>

                    <button type="submit" class="btn btn-primary" style="width: 100%">{% if element == 'ajouter' %}ajouter{% else %}modifier{% endif %}</button>
                    {{ form_end(form) }}
                </div>
            </div>

        </div>
    </div>

    <!-- Form End -->

{% endblock %}
{% block js %}
    <script>
        const form = document.querySelector('.modLiv')
        const input = document.querySelector('.dest')
        const errorP = document.querySelector('.error')
        form.addEventListener('submit',e=>{
            if(input.value==""){
                e.preventDefault()
                errorP.style.display = "block"




            }

        })


    </script>
{% endblock %}